sudo: required
language: python
python: 
- "2.7"
- "3.5"

services:
  - docker

before_install: 
  - ./scripts/start_docker.sh
  - ./scripts/wait_until_oracle_ready.sh
  - ./scripts/download_dependencies.sh

script: ./test/run_all_tests.py
